version: "3.7"
services:
  web:
    container_name: campaign_manager_nginx
    image: nginx:1.19.3
    ports:
      - "${NGINX_INSECURE_PORT}:80"
    volumes:
      - ../:/var/www
      - ./setup/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./setup/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      campaign_manager:
  php:
    container_name: campaign_manager_php
    build: ./setup/php/
    volumes:
      - ../:/var/www
      - ./setup/nginx/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
      - redis
    networks:
      campaign_manager:
  db:
    container_name: campaign_manager_mysql
    image: mysql:8.0.21
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "${MYSQL_DATA_DIR}:/var/lib/mysql"
    restart: always
    env_file:
      - .env
    networks:
      campaign_manager:
  redis:
    container_name: campaign_manager_redis
    image: redis:6.0.8
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${REDIS_DATA_DIR}:/bitnami/redis/data"
    networks:
      campaign_manager:

networks:
  campaign_manager:
    ipam:
      config:
        - subnet: 192.168.9.0/24
